### ISSUE TITLE
Hoes Counter Broken Fatally

### ISSUE THREAD

**Issue by FriendlyGamer** [louisroyer/minetest-toolranks-extras#9]
Trace Stack and crash upon farming on using the builtin 5.3 MTG's Farming mod... 

> 2020-08-18 20:34:55: ACTION[Main]: Server: Shutting down 2020-08-18 20:35:00: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'farming' in callback item_OnUse(): Invalid position (expected table got nil). 2020-08-18 20:35:00: ERROR[Main]: stack traceback: 2020-08-18 20:35:00: ERROR[Main]: [C]: in function 'get_node' 2020-08-18 20:35:00: ERROR[Main]: /home/ritorres/.minetest/mods/toolranks_extras/hoe.lua:17: in function 

From the trace the suspected fatal snippet is... 
```
-- we also want hoes to increase dugnodes when farming soil  
on_use = function(itemstack, user, pointed_thing, uses) local under = minetest.get_node(pointed_thing.under)
``` 
Until this issue is isolated and fixated I cannot honestly be running a server where a crash can happen just because someone is tilling dirt and it causes a crash somehow. As this person was just doing some normal good old farming they said.

**Comment by louisroyer** [comment]
I added a nil check so this cannot happen anymore.
Your player probably clicked on air or on an item using the hoe, and unfortunately I had forgotten this case.
Version 1.4.2 contains the fix, sorry for the inconvenience. If you still have crash even with the fix, please reopen this issue.
